"use strict";

const assert = require("node:assert/strict");
const fs = require("node:fs");
const path = require("node:path");
const test = require("node:test");

const root = path.resolve(__dirname, "../..");
const read = (relative) => JSON.parse(fs.readFileSync(path.join(root, relative), "utf8"));

test("strict verification registry schemas match the materialized Phase 0 artifacts", () => {
    const manifest = read("games/genshin/data/data-v2-manifest.json");
    assert.equal(manifest.datasets.r2AcceptanceInventory.authority, "finiteAcceptanceInventory");
    assert.equal(manifest.datasets.r2WorkDispositions.authority, "workDispositionOnly");
    assert.equal(read("games/genshin/data/" + manifest.datasets.r2WorkDispositions.path).kind, "genshinR2WorkDispositionRegistry");
    assert.equal(manifest.datasets.behaviorModifierLaneAudit.authority, "evidenceChainReconciliation");
    assert.equal(manifest.datasets.talentGapLaneAudit.authority, "evidenceChainReconciliation");
    assert.equal(manifest.datasets.localizedCharacterIdentityBridge.authority, "providerLocalizedIdentityEvidenceOnly");
    assert.ok(manifest.datasets.localizedCharacterIdentityBridgeCheckpoint.path);
    assert.equal(manifest.datasets.talentGapLocalizedFieldBridge.authority, "providerLocalizedFieldIdentityEvidenceOnly");
    assert.equal(manifest.datasets.talentGapLocalizedFieldBridgeCheckpoint.authority, "providerCaptureCheckpoint");
    assert.equal(manifest.datasets.candidateSourceCoverageFrontierInventory.authority, "candidateSourceCoverageEvidenceOnly");
    assert.equal(manifest.datasets.officialWeaponFrontier11301To11303.authority, "mutableOfficialFieldAvailabilityOnly");
    const certificates = read("games/genshin/data/v2/eligibility-certificates.json");
    const attestations = read("games/genshin/data/v2/deterministic-attestations.json");
    const families = read("games/genshin/data/v2/source-family-registry.json");
    const versionBaseline = read("games/genshin/data/v2/version-baseline.json");
    const upstreamVersionHead = read("games/genshin/data/v2/upstream-version-head.json");
    for (const key of ["eligibilityCertificates", "deterministicAttestations", "sourceFamilyRegistry", "versionBaseline", "upstreamVersionHead", "sourceSearchFrontiers", "characterIdentityConsistencyAudit", "versionTransitionBehaviorEntitySnapshot", "versionTransitionBehaviorEntitySnapshotShard02", "versionTransitionBehaviorEntitySnapshotShard03", "versionTransitionBehaviorEntityCaptureCheckpointShard03", "versionTransitionBehaviorEntitySnapshotShard04", "versionTransitionBehaviorEntityCaptureCheckpointShard04", "versionTransitionBehaviorEntitySnapshotShard05", "versionTransitionBehaviorEntityCaptureCheckpointShard05", "versionTransitionBehaviorEntitySnapshotShard06", "versionTransitionBehaviorEntityCaptureCheckpointShard06", "versionTransitionBehaviorEntitySnapshotShard07", "versionTransitionBehaviorEntityCaptureCheckpointShard07", "versionTransitionBehaviorEntitySnapshotShard08", "versionTransitionBehaviorEntityCaptureCheckpointShard08", "versionTransitionBehaviorEntitySnapshotShard09", "versionTransitionBehaviorEntityCaptureCheckpointShard09", "versionTransitionBehaviorEntitySnapshotShard10", "versionTransitionBehaviorEntityCaptureCheckpointShard10", "versionTransitionBehaviorEntitySnapshotShard11", "versionTransitionBehaviorEntityCaptureCheckpointShard11", "versionTransitionBehaviorEntitySnapshotShard12", "versionTransitionBehaviorEntityCaptureCheckpointShard12", "versionTransitionBehaviorEntitySnapshotShard13", "versionTransitionBehaviorEntityCaptureCheckpointShard13", "versionTransitionBehaviorEntitySnapshotShard14", "versionTransitionBehaviorEntityCaptureCheckpointShard14", "versionTransitionBehaviorEntitySnapshotShard15", "versionTransitionBehaviorEntityCaptureCheckpointShard15", "versionTransitionBehaviorEntitySnapshotShard16", "versionTransitionBehaviorEntityCaptureCheckpointShard16", "versionTransitionWeaponEntitySnapshot", "versionTransitionWeaponEntityCaptureCheckpoint", "versionTransitionWeaponEntitySnapshotShard02", "versionTransitionWeaponEntityCaptureCheckpointShard02", "versionTransitionWeaponEntitySnapshotShard03", "versionTransitionWeaponEntityCaptureCheckpointShard03", "versionTransitionWeaponEntitySnapshotShard04", "versionTransitionWeaponEntityCaptureCheckpointShard04"]) {
        assert.ok(manifest.datasets[key]?.path);
    }
    assert.equal(certificates.kind, "genshinClaimEligibilityCertificateRegistry");
    assert.equal(certificates.summary.eligibleCount, certificates.certificates.filter((item) => item.status === "eligible").length);
    assert.equal(attestations.kind, "genshinDeterministicConsensusAttestationRegistry");
    assert.equal(attestations.summary.attestations, attestations.attestations.length);
    assert.equal(families.kind, "genshinSourceFamilyRegistry");
    assert.equal(versionBaseline.kind, "genshinAcceptedVersionBaseline");
    assert.equal(upstreamVersionHead.kind, "genshinUpstreamVersionHead");

    const certificateSchema = read("games/genshin/data/schema/eligibility-certificates.schema.json");
    const attestationSchema = read("games/genshin/data/schema/deterministic-attestations.schema.json");
    const familySchema = read("games/genshin/data/schema/source-family-registry.schema.json");
    const versionBaselineSchema = read("games/genshin/data/schema/version-baseline.schema.json");
    const upstreamVersionHeadSchema = read("games/genshin/data/schema/upstream-version-head.schema.json");
    const versionEntityDiffSchema = read("games/genshin/data/schema/version-entity-diff.schema.json");
    const versionDiscoverySchema = read("games/genshin/data/schema/version-transition-discovery.schema.json");
    const versionClaimQueueSchema = read("games/genshin/data/schema/version-transition-claim-reacquisition.schema.json");
    const versionTargetDatasetSchema = read("games/genshin/data/schema/version-transition-target-dataset-evidence.schema.json");
    const versionAffectedEntitySchema = read("games/genshin/data/schema/version-transition-affected-entity-snapshot.schema.json");
    const sourceSearchFrontierSchema = read("games/genshin/data/schema/source-search-frontiers.schema.json");
    const behaviorEntitySnapshotSchema = read("games/genshin/data/schema/version-transition-behavior-entity-snapshot.schema.json");
    const behaviorShardSnapshotSchema = read("games/genshin/data/schema/version-transition-behavior-shard-snapshot.schema.json");
    const behaviorShard03SnapshotSchema = read("games/genshin/data/schema/version-transition-behavior-shard03-snapshot.schema.json");
    const behaviorShard03CheckpointSchema = read("games/genshin/data/schema/version-transition-behavior-shard03-capture-checkpoint.schema.json");
    const behaviorShard04SnapshotSchema = read("games/genshin/data/schema/version-transition-behavior-shard-04-snapshot.schema.json");
    const behaviorShardCheckpointSchema = read("games/genshin/data/schema/version-transition-behavior-shard-capture-checkpoint.schema.json");
    const behaviorShard05SnapshotSchema = read("games/genshin/data/schema/version-transition-behavior-shard-05-snapshot.schema.json");
    const behaviorShard05CheckpointSchema = read("games/genshin/data/schema/version-transition-behavior-shard-05-capture-checkpoint.schema.json");
    const behaviorShard06SnapshotSchema = read("games/genshin/data/schema/version-transition-behavior-shard06-snapshot.schema.json");
    const behaviorShard06CheckpointSchema = read("games/genshin/data/schema/version-transition-behavior-shard06-capture-checkpoint.schema.json");
    const behaviorShard07SnapshotSchema = read("games/genshin/data/schema/version-transition-behavior-shard-07-snapshot.schema.json");
    const behaviorShard08SnapshotSchema = read("games/genshin/data/schema/version-transition-behavior-shard-08-snapshot.schema.json");
    const behaviorShard09SnapshotSchema = read("games/genshin/data/schema/version-transition-behavior-shard-09-snapshot.schema.json");
    const behaviorShard10SnapshotSchema = read("games/genshin/data/schema/version-transition-behavior-shard-10-snapshot.schema.json");
    const behaviorShard10CheckpointSchema = read("games/genshin/data/schema/version-transition-behavior-shard-10-capture-checkpoint.schema.json");
    const behaviorShard11SnapshotSchema = read("games/genshin/data/schema/version-transition-behavior-shard-11-snapshot.schema.json");
    const behaviorShard11CheckpointSchema = read("games/genshin/data/schema/version-transition-behavior-shard-11-capture-checkpoint.schema.json");
    const behaviorShard12SnapshotSchema = read("games/genshin/data/schema/version-transition-behavior-shard-12-snapshot.schema.json");
    const behaviorShard12CheckpointSchema = read("games/genshin/data/schema/version-transition-behavior-shard-12-capture-checkpoint.schema.json");
    const behaviorShard13SnapshotSchema = read("games/genshin/data/schema/version-transition-behavior-shard-13-snapshot.schema.json");
    const behaviorShard13CheckpointSchema = read("games/genshin/data/schema/version-transition-behavior-shard-13-capture-checkpoint.schema.json");
    const behaviorShard14SnapshotSchema = read("games/genshin/data/schema/version-transition-behavior-shard-14-snapshot.schema.json");
    const behaviorShard14CheckpointSchema = read("games/genshin/data/schema/version-transition-behavior-shard-14-capture-checkpoint.schema.json");
    const behaviorShard15SnapshotSchema = read("games/genshin/data/schema/version-transition-behavior-shard-15-snapshot.schema.json");
    const behaviorShard15CheckpointSchema = read("games/genshin/data/schema/version-transition-behavior-shard-15-capture-checkpoint.schema.json");
    const behaviorShard16SnapshotSchema = read("games/genshin/data/schema/version-transition-behavior-shard-16-snapshot.schema.json");
    const behaviorShard16CheckpointSchema = read("games/genshin/data/schema/version-transition-behavior-shard-16-capture-checkpoint.schema.json");
    const characterIdentityConsistencySchema = read("games/genshin/data/schema/genshin-character-identity-consistency-audit.schema.json");
    const weaponEntitySnapshotSchema = read("games/genshin/data/schema/version-transition-weapon-entity-snapshot.schema.json");
    const weaponEntityCheckpointSchema = read("games/genshin/data/schema/version-transition-weapon-entity-capture-checkpoint.schema.json");
    assert.match(JSON.stringify(certificateSchema), /strictGameVersionBinding/);
    assert.match(JSON.stringify(certificateSchema), /rawArtifactDigest/);
    assert.match(JSON.stringify(certificateSchema), /sourceBundleDigest/);
    assert.match(JSON.stringify(attestationSchema), /eligibilityCertificateId/);
    assert.match(JSON.stringify(attestationSchema), /requiredFieldSetDigest/);
    assert.match(JSON.stringify(familySchema), /lineageEvidenceRefs/);
    assert.match(JSON.stringify(familySchema), /datamineRoot/);
    assert.match(JSON.stringify(versionBaselineSchema), /previousSnapshotId/);
    assert.match(JSON.stringify(upstreamVersionHeadSchema), /rawApiResponseDigest/);
    assert.match(JSON.stringify(upstreamVersionHeadSchema), /fieldDigest/);
    assert.match(JSON.stringify(versionEntityDiffSchema), /candidateInventoryDigest/);
    assert.match(JSON.stringify(versionEntityDiffSchema), /strictlyBound/);
    assert.match(JSON.stringify(versionEntityDiffSchema), /rawArtifactDigest/);
    assert.match(JSON.stringify(versionDiscoverySchema), /discoveryOnlyFailClosed/);
    assert.match(JSON.stringify(versionDiscoverySchema), /conservativeEntityInvalidation/);
    assert.match(JSON.stringify(versionClaimQueueSchema), /preparationOnlyFailClosed/);
    assert.match(JSON.stringify(versionClaimQueueSchema), /claimSchemaStatus/);
    assert.match(JSON.stringify(versionTargetDatasetSchema), /canSatisfyCompleteEntityDiff/);
    assert.match(JSON.stringify(versionAffectedEntitySchema), /providerDiffOnlyFailClosed/);
    assert.match(JSON.stringify(sourceSearchFrontierSchema), /candidateIdDigest/);
    assert.match(JSON.stringify(sourceSearchFrontierSchema), /reopenTrigger/);
    assert.match(JSON.stringify(behaviorEntitySnapshotSchema), /unresolvedVariantAmbiguity/);
    assert.match(JSON.stringify(behaviorShardSnapshotSchema), /authoritativeCandidateIdsDigest/);
    assert.match(JSON.stringify(behaviorShard03SnapshotSchema), /singleCorrelatedFamilyFailClosed/);
    assert.match(JSON.stringify(behaviorShard03CheckpointSchema), /nextTask/);
    assert.match(JSON.stringify(behaviorShard04SnapshotSchema), /skippedOverlapEntityIds/);
    assert.match(JSON.stringify(behaviorShardCheckpointSchema), /completedArtifactCount/);
    assert.match(JSON.stringify(behaviorShard05SnapshotSchema), /skippedOverlapEntityIds/);
    assert.match(JSON.stringify(behaviorShard05CheckpointSchema), /nextTask/);
    assert.match(JSON.stringify(behaviorShard06SnapshotSchema), /singleCorrelatedFamilyFailClosed/);
    assert.match(JSON.stringify(behaviorShard06CheckpointSchema), /completedArtifactCount/);
    assert.match(JSON.stringify(behaviorShard07SnapshotSchema), /overlapEvidence/);
    assert.match(JSON.stringify(behaviorShard08SnapshotSchema), /authoritativeCandidateIdsDigest/);
    assert.match(JSON.stringify(behaviorShard09SnapshotSchema), /authoritativeCandidateIdsDigest/);
    assert.match(JSON.stringify(behaviorShard10SnapshotSchema), /authoritativeCandidateIdsDigest/);
    assert.match(JSON.stringify(behaviorShard10CheckpointSchema), /authoritativeCandidateIdsDigest/);
    assert.match(JSON.stringify(behaviorShard11SnapshotSchema), /authoritativeCandidateIdsDigest/);
    assert.match(JSON.stringify(behaviorShard11CheckpointSchema), /authoritativeCandidateIdsDigest/);
    assert.match(JSON.stringify(behaviorShard12SnapshotSchema), /authoritativeCandidateIdsDigest/);
    assert.match(JSON.stringify(behaviorShard12CheckpointSchema), /authoritativeCandidateIdsDigest/);
    assert.match(JSON.stringify(behaviorShard13SnapshotSchema), /authoritativeCandidateIdsDigest/);
    assert.match(JSON.stringify(behaviorShard13CheckpointSchema), /authoritativeCandidateIdsDigest/);
    assert.match(JSON.stringify(behaviorShard14SnapshotSchema), /authoritativeCandidateIdsDigest/);
    assert.match(JSON.stringify(behaviorShard14CheckpointSchema), /authoritativeCandidateIdsDigest/);
    assert.match(JSON.stringify(behaviorShard15SnapshotSchema), /authoritativeCandidateIdsDigest/);
    assert.match(JSON.stringify(behaviorShard15CheckpointSchema), /authoritativeCandidateIdsDigest/);
    assert.match(JSON.stringify(behaviorShard16SnapshotSchema), /authoritativeCandidateIdsDigest/);
    assert.match(JSON.stringify(behaviorShard16CheckpointSchema), /authoritativeCandidateIdsDigest/);
    assert.match(JSON.stringify(characterIdentityConsistencySchema), /identitySensitivePromotion/);
    assert.match(JSON.stringify(weaponEntitySnapshotSchema), /singleCorrelatedFamilyFailClosed/);
    assert.match(JSON.stringify(weaponEntityCheckpointSchema), /nextTask/);
    assert.match(JSON.stringify(certificateSchema), /versionSnapshotId/);
});

test("runtime and state schemas distinguish human review from deterministic consensus", () => {
    const runtimeSchema = read("games/genshin/data/v2/runtime/contract.schema.json");
    const stateSchema = read("games/genshin/data/schema/verification-state.schema.json");
    const runtimeText = JSON.stringify(runtimeSchema);
    assert.match(runtimeText, /deterministicConsensus/);
    assert.match(runtimeText, /claimProofs/);
    assert.match(runtimeText, /sourceBundleDigest/);
    assert.equal(runtimeSchema.properties.provenance.properties.verification.properties.claimProofs.type, "object");
    assert.deepEqual(stateSchema.properties.verificationMode.enum, ["human", "deterministicConsensus"]);
});
