"use strict";

/**
 * Materialize authoritative behaviorSpec shard 06 source records.
 *
 * This worker is intentionally limited to immutable source capture and a
 * deterministic 6.7 -> 7.0 comparison.  It does not parse descriptions into
 * behavior fields, make a provider-independence claim, issue a certificate,
 * or promote Runtime/canonical data.  The queue currently labels this shard
 * semanticDecisionRequired; that observed lane is retained verbatim.
 */

const fs = require("node:fs");
const path = require("node:path");
const crypto = require("node:crypto");
const { digestStable } = require("./genshinVersionEvidenceValidation.cjs");

const repositoryRoot = path.resolve(__dirname, "..");
const transitionRoot = path.join(repositoryRoot, "games", "genshin", "data", "v2", "version-transitions", "6.7-to-7.0");
const providerRoot = path.join(transitionRoot, "sources", "genshin-db-shard06");
const queuePath = path.join(repositoryRoot, "reports", "genshin-evidence-task-queue.json");
const outputPath = path.join(transitionRoot, "behavior-shard-06-snapshot.json");
const checkpointPath = path.join(transitionRoot, "behavior-shard-06-capture-checkpoint.json");
const generatedAt = "2026-08-26T00:00:00.000Z";
const repository = "theBowja/genshin-db";
const provider = "genshin-db";
const sourceFamily = "GenshinData-derived";
const recordKinds = ["talents", "constellations"];
const shardId = "behavior:behaviorSpec:semanticDecisionRequired:standard:06";
const requestedPrimaryBlockReason = "sourceMissing";
const observedPrimaryBlockReason = "semanticDecisionRequired";
const queuePathRelative = path.relative(repositoryRoot, queuePath).replaceAll("\\", "/");
const overlapEntityIds = [];

const revisions = {
    before: {
        gameVersion: "6.7",
        revision: "1bab2cdba4d218fd5caa46b5f54e7884ee8359a2",
        packageVersion: "5.2.12",
        packagePath: "package.json",
        packageDigest: "5ded2b3bab58218da17f6a1282209e653c1ec7ecd9297b95569558a737c2e8f6",
        packageBytes: 1619,
        packageBlob: "e78cc92e75db21ea15edadbeafdf9152896d934c"
    },
    after: {
        gameVersion: "7.0",
        revision: "8b15995fa220c88a4d0d7ffe1e21b041d0b32588",
        packageVersion: "5.2.13",
        packagePath: "package.json",
        packageDigest: "3faf0b2220539a07af9260f5dd83afd0e964aa42868c9b3b73c6cb14065085c6",
        packageBytes: 1619,
        packageBlob: "cfccefd470f420159b1376440e1a0f86a247030d"
    }
};

// These concrete provider slugs were read-only validated against the pinned
// 6.7 raw tree before this script was created.  They are not generated by a
// fuzzy translation or by a Japanese display-name search.
const resolvedEntities = [
    { entityId: "10000054", name: "Sangonomiya Kokomi", nameJa: "珊瑚宮心海", slug: "sangonomiyakokomi" },
    { entityId: "10000055", name: "Gorou", nameJa: "ゴロー", slug: "gorou" },
    { entityId: "10000056", name: "Kujou Sara", nameJa: "九条裟羅", slug: "kujousara" },
    { entityId: "10000057", name: "Arataki Itto", nameJa: "荒瀧一斗", slug: "aratakiitto" },
    { entityId: "10000059", name: "Shikanoin Heizou", nameJa: "鹿野院平蔵", slug: "shikanoinheizou" },
    { entityId: "10000060", name: "Yelan", nameJa: "夜蘭", slug: "yelan" },
    { entityId: "10000062", name: "Aloy", nameJa: "アーロイ", slug: "aloy" },
    { entityId: "10000063", name: "Shenhe", nameJa: "申鶴", slug: "shenhe" }
];

function sha256(bytes) {
    return crypto.createHash("sha256").update(bytes).digest("hex");
}

function gitBlobSha(bytes) {
    const header = Buffer.from(`blob ${bytes.length}\0`, "utf8");
    return crypto.createHash("sha1").update(Buffer.concat([header, bytes])).digest("hex");
}

function readJson(file) {
    return JSON.parse(fs.readFileSync(file, "utf8"));
}

function relative(file) {
    return path.relative(repositoryRoot, file).replaceAll("\\", "/");
}

function sourcePath(revision, recordKind, slug) {
    return path.join(providerRoot, revision, "English", recordKind, `${slug}.json`);
}

function sourceUrl(revision, recordKind, slug) {
    return `https://raw.githubusercontent.com/${repository}/${revision}/src/data/English/${recordKind}/${slug}.json`;
}

function packageFile(revision) {
    return path.join(providerRoot, revision.revision, revision.packagePath);
}

function queueShard() {
    const queue = readJson(queuePath);
    const clusters = (queue.unlockClusters || []).filter((item) => item.domain === "behavior" && item.layer === "behaviorSpec");
    const shards = clusters.flatMap((cluster) => cluster.shards || []);
    const shard = shards.find((candidate) => String(candidate?.shardId || "") === shardId);
    if (!shard || !Array.isArray(shard.candidateIds) || shard.candidateIds.length !== 100) {
        throw new Error(`authoritative behaviorSpec shard 06 missing or count is not 100: ${shardId}`);
    }
    const candidateIds = shard.candidateIds.map(String);
    if (new Set(candidateIds).size !== candidateIds.length || !candidateIds.every((id) => /^behavior:100000\d+:/.test(id))) {
        throw new Error("authoritative behaviorSpec shard 06 candidate IDs are malformed or duplicated");
    }
    const entityIds = [...new Set(candidateIds.map((candidateId) => candidateId.split(":")[1]))];
    const expectedEntityIds = resolvedEntities.map((entity) => entity.entityId);
    if (entityIds.length !== expectedEntityIds.length || digestStable(entityIds) !== digestStable(expectedEntityIds)) {
        throw new Error(`shard 06 entity inventory mismatch: ${entityIds.join(",")}`);
    }
    return {
        shardId,
        queuePath: queuePathRelative,
        requestedPrimaryBlockReason,
        observedPrimaryBlockReason,
        candidateIds,
        candidateIdsDigest: digestStable(candidateIds),
        entityIds,
        entityIdsDigest: digestStable(entityIds),
        candidateCount: candidateIds.length,
        entityCount: entityIds.length
    };
}

async function fetchBytes(url) {
    const response = await fetch(url, { headers: { "User-Agent": "damageTool-genshin-behavior-shard-06" } });
    if (!response.ok) {
        const error = new Error(`fetch failed ${response.status}: ${url}`);
        error.status = response.status;
        throw error;
    }
    return Buffer.from(await response.arrayBuffer());
}

function assertExpectedPackage(revision, bytes) {
    if (bytes.length !== revision.packageBytes) throw new Error(`${revision.gameVersion} package bytes mismatch`);
    if (sha256(bytes) !== revision.packageDigest) throw new Error(`${revision.gameVersion} package SHA-256 mismatch`);
    if (gitBlobSha(bytes) !== revision.packageBlob) throw new Error(`${revision.gameVersion} package Git blob mismatch`);
    const manifest = JSON.parse(bytes.toString("utf8"));
    if (manifest.name !== provider || manifest.version !== revision.packageVersion) throw new Error(`${revision.gameVersion} package version mismatch`);
    if (!String(manifest.description || "").includes(`Genshin Impact v${revision.gameVersion} JSON data`)) throw new Error(`${revision.gameVersion} strict game-version text missing`);
    if (!String(manifest.description || "").includes("fandom wiki and GenshinData repo")) throw new Error(`${revision.gameVersion} lineage text missing`);
    return manifest;
}

function assertEntityRecord(entity, recordKind, bytes) {
    const value = JSON.parse(bytes.toString("utf8"));
    if (value?.name !== entity.name) throw new Error(`${entity.entityId}:${recordKind} provider name mismatch: ${value?.name}`);
    if (!Number.isInteger(value?.id)) throw new Error(`${entity.entityId}:${recordKind} provider record id missing`);
    return value;
}

async function acquire() {
    queueShard();
    for (const revision of Object.values(revisions)) {
        const root = path.join(providerRoot, revision.revision);
        fs.mkdirSync(root, { recursive: true });
        const manifestBytes = await fetchBytes(`https://raw.githubusercontent.com/${repository}/${revision.revision}/${revision.packagePath}`);
        assertExpectedPackage(revision, manifestBytes);
        fs.writeFileSync(packageFile(revision), manifestBytes);
        for (const entity of resolvedEntities) {
            for (const recordKind of recordKinds) {
                const bytes = await fetchBytes(sourceUrl(revision.revision, recordKind, entity.slug));
                assertEntityRecord(entity, recordKind, bytes);
                const file = sourcePath(revision.revision, recordKind, entity.slug);
                fs.mkdirSync(path.dirname(file), { recursive: true });
                fs.writeFileSync(file, bytes);
            }
        }
    }
}

function pointerToken(value) {
    return String(value).replaceAll("~", "~0").replaceAll("/", "~1");
}

function fieldDigest(value) {
    return digestStable(value === undefined ? null : value);
}

function fieldDiffs(before, after, pointer = "") {
    if (fieldDigest(before) === fieldDigest(after)) return [];
    const beforeObject = before && typeof before === "object";
    const afterObject = after && typeof after === "object";
    if (!beforeObject || !afterObject || Array.isArray(before) !== Array.isArray(after)) {
        return [{
            jsonPointer: pointer || "/",
            beforeValue: before === undefined ? null : before,
            afterValue: after === undefined ? null : after,
            beforeFieldDigest: fieldDigest(before),
            afterFieldDigest: fieldDigest(after)
        }];
    }
    const keys = Array.isArray(before) && Array.isArray(after)
        ? Array.from({ length: Math.max(before.length, after.length) }, (_, index) => String(index))
        : [...new Set([...Object.keys(before || {}), ...Object.keys(after || {})])].sort();
    return keys.flatMap((key) => fieldDiffs(before?.[key], after?.[key], `${pointer}/${pointerToken(key)}`));
}

function embeddedCharacterIds(value) {
    const ids = new Set();
    const visit = (node) => {
        if (!node || typeof node !== "object") return;
        if (Array.isArray(node)) {
            node.forEach(visit);
            return;
        }
        for (const [key, child] of Object.entries(node)) {
            if (/^characterId$/i.test(key) && /^100000\d+$/.test(String(child))) ids.add(String(child));
            visit(child);
        }
    };
    visit(value);
    return [...ids].sort();
}

function artifact(revision, entity, recordKind) {
    const file = sourcePath(revision.revision, recordKind, entity.slug);
    if (!fs.existsSync(file)) throw new Error(`captured source missing: ${relative(file)}`);
    const bytes = fs.readFileSync(file);
    const value = assertEntityRecord(entity, recordKind, bytes);
    const embeddedIds = embeddedCharacterIds(value);
    return {
        gameVersion: revision.gameVersion,
        revision: revision.revision,
        packageVersion: revision.packageVersion,
        providerPath: `src/data/English/${recordKind}/${entity.slug}.json`,
        path: relative(file),
        url: sourceUrl(revision.revision, recordKind, entity.slug),
        providerRecordId: value.id,
        embeddedCharacterIds: embeddedIds,
        embeddedCharacterIdStatus: embeddedIds.length ? "present" : "notProvidedByProviderRecord",
        gitBlob: gitBlobSha(bytes),
        rawArtifactBytes: bytes.length,
        rawArtifactSha256: sha256(bytes),
        normalizedRecordDigest: digestStable(value)
    };
}

function packageEvidence(revision) {
    const file = packageFile(revision);
    if (!fs.existsSync(file)) throw new Error(`captured package manifest missing: ${relative(file)}`);
    const bytes = fs.readFileSync(file);
    const manifest = assertExpectedPackage(revision, bytes);
    return {
        gameVersion: revision.gameVersion,
        revision: revision.revision,
        packageVersion: revision.packageVersion,
        path: relative(file),
        url: `https://raw.githubusercontent.com/${repository}/${revision.revision}/${revision.packagePath}`,
        gitBlob: gitBlobSha(bytes),
        rawArtifactBytes: bytes.length,
        rawArtifactSha256: sha256(bytes),
        name: manifest.name,
        description: manifest.description
    };
}

function recordComparison(before, after) {
    const beforeValue = readJson(path.resolve(repositoryRoot, before.path));
    const afterValue = readJson(path.resolve(repositoryRoot, after.path));
    const diffs = fieldDiffs(beforeValue, afterValue);
    return {
        status: diffs.length ? "rawRecordChanged" : "rawRecordMatch",
        beforeNormalizedRecordDigest: digestStable(beforeValue),
        afterNormalizedRecordDigest: digestStable(afterValue),
        changedFieldCount: diffs.length,
        fieldDiffs: diffs
    };
}

function buildEntity(entity) {
    const records = recordKinds.map((recordKind) => {
        const before = artifact(revisions.before, entity, recordKind);
        const after = artifact(revisions.after, entity, recordKind);
        return { recordKind, before, after, comparison: recordComparison(before, after) };
    });
    return {
        entityId: entity.entityId,
        name: entity.name,
        nameJa: entity.nameJa,
        providerSlug: entity.slug,
        resolutionStatus: "resolvedUnambiguousByProviderName",
        providerEntityIdEvidence: "provider record has no characterId field; local entity ID is queue-bound and provider name/path validated",
        treeResolution: {
            method: "pinnedProviderPathWithEmbeddedRecordIdentity",
            directoryPaths: recordKinds.map((recordKind) => `src/data/English/${recordKind}`),
            pathResolution: recordKinds.map((recordKind) => ({
                recordKind,
                path: `src/data/English/${recordKind}/${entity.slug}.json`
            }))
        },
        records
    };
}

function buildClaim() {
    const queue = queueShard();
    const resolved = resolvedEntities.map(buildEntity);
    const allRecords = resolved.flatMap((entity) => entity.records);
    const changedRecords = allRecords.filter((record) => record.comparison.status === "rawRecordChanged");
    const changedFields = allRecords.reduce((sum, record) => sum + record.comparison.changedFieldCount, 0);
    return {
        transitionId: "genshin:6.7->7.0",
        fromGameVersion: revisions.before.gameVersion,
        toGameVersion: revisions.after.gameVersion,
        provider,
        sourceFamily,
        repository,
        sourceFamilyCount: 1,
        queueShard: {
            shardId: queue.shardId,
            queuePath: queue.queuePath,
            requestedPrimaryBlockReason: queue.requestedPrimaryBlockReason,
            observedPrimaryBlockReason: queue.observedPrimaryBlockReason,
            authoritativeCandidateCount: queue.candidateCount,
            authoritativeCandidateIds: queue.candidateIds,
            authoritativeCandidateIdsDigest: queue.candidateIdsDigest,
            authoritativeEntityCount: queue.entityCount,
            authoritativeEntityIds: queue.entityIds,
            authoritativeEntityIdsDigest: queue.entityIdsDigest,
            overlapEntityIds,
            overlapPolicy: "noneWithMaterializedBehaviorShards01To04"
        },
        versionBindings: Object.values(revisions).map((revision) => ({
            gameVersion: revision.gameVersion,
            revision: revision.revision,
            packageVersion: revision.packageVersion,
            status: "strictlyBound",
            package: packageEvidence(revision)
        })),
        resolvedEntities: resolved,
        travelerVariantEvidence: [],
        variantAmbiguities: [],
        coverage: {
            resolvedEntityIds: resolvedEntities.map((entity) => entity.entityId),
            ambiguousEntityIds: [],
            recordKinds,
            authoritativeCandidateCoverage: "entitySourceRecordsComplete",
            resolvedEntityRecordCoverage: "complete",
            travelerVariantRecordCoverage: "notApplicable",
            embeddedCharacterIdCoverage: "providerRecordDoesNotEmbedEntityId",
            repositoryCandidateCoverage: "partial",
            authoritativeCandidateCount: queue.candidateCount,
            authoritativeEntityCount: queue.entityCount,
            resolvedEntityCount: resolved.length,
            resolvedRecordCount: allRecords.length,
            changedRecordCount: changedRecords.length,
            changedFieldCount: changedFields,
            overlapEntityCount: overlapEntityIds.length,
            crossVariantComparisons: 0,
            canIssueEligibilityCertificate: false,
            canPromoteCanonical: false
        }
    };
}

function buildSnapshot() {
    const claim = buildClaim();
    const allRecords = claim.resolvedEntities.flatMap((entity) => entity.records);
    const changedRecords = allRecords.filter((record) => record.comparison.status === "rawRecordChanged");
    const changedFields = allRecords.reduce((sum, record) => sum + record.comparison.changedFieldCount, 0);
    return {
        schemaVersion: 1,
        kind: "genshinVersionTransitionBehaviorShard06Snapshot",
        generatedAt,
        claim,
        summary: {
            shardId: claim.queueShard.shardId,
            authoritativeCandidates: claim.queueShard.authoritativeCandidateCount,
            authoritativeEntities: claim.queueShard.authoritativeEntityCount,
            resolvedEntities: claim.resolvedEntities.length,
            overlapSkippedEntities: overlapEntityIds.length,
            ambiguousEntities: claim.variantAmbiguities.length,
            resolvedRecords: allRecords.length,
            changedRecords: changedRecords.length,
            changedFields,
            sourceFamilyCount: 1,
            certificateEligibleClaims: 0
        },
        gateEligibility: {
            status: "singleCorrelatedFamilyFailClosed",
            sourceFamilyCount: 1,
            canIssueEligibilityCertificate: false,
            canPromoteCanonical: false,
            reasons: ["providerIndependenceInsufficient", "behaviorSemanticsNotParsed", "noIndependentSourceFamily"]
        },
        fieldDigestAlgorithm: "sha256-stable-json-v1",
        fieldDigest: digestStable(claim)
    };
}

function validateArtifact(candidate, revision, entity, recordKind, root = repositoryRoot) {
    const reasons = [];
    const file = candidate?.path ? path.resolve(root, candidate.path) : null;
    const expected = sourcePath(revision.revision, recordKind, entity.slug);
    if (!file || path.resolve(file) !== path.resolve(expected)) reasons.push("pathMismatch");
    if (!file || !fs.existsSync(file)) return [...reasons, "missing"];
    const bytes = fs.readFileSync(file);
    let value;
    try {
        value = assertEntityRecord(entity, recordKind, bytes);
    } catch (error) {
        reasons.push(`identityMismatch:${error.message}`);
    }
    if (candidate.gameVersion !== revision.gameVersion || candidate.revision !== revision.revision || candidate.packageVersion !== revision.packageVersion) reasons.push("versionBindingMismatch");
    if (candidate.providerPath !== `src/data/English/${recordKind}/${entity.slug}.json`) reasons.push("providerPathMismatch");
    if (candidate.rawArtifactBytes !== bytes.length) reasons.push("bytesMismatch");
    if (candidate.rawArtifactSha256 !== sha256(bytes)) reasons.push("sha256Mismatch");
    if (candidate.gitBlob !== gitBlobSha(bytes)) reasons.push("gitBlobMismatch");
    if (value && candidate.providerRecordId !== value.id) reasons.push("providerRecordIdMismatch");
    if (value && digestStable(value) !== candidate.normalizedRecordDigest) reasons.push("normalizedDigestMismatch");
    if (value && digestStable(embeddedCharacterIds(value)) !== digestStable(candidate.embeddedCharacterIds)) reasons.push("embeddedCharacterIdsMismatch");
    return reasons;
}

function validateBehaviorShard06Snapshot(snapshot, { repositoryRoot: root = repositoryRoot } = {}) {
    const reasons = [];
    if (snapshot?.schemaVersion !== 1 || snapshot?.kind !== "genshinVersionTransitionBehaviorShard06Snapshot") reasons.push("identityInvalid");
    if (snapshot?.generatedAt !== generatedAt) reasons.push("generatedAtInvalid");
    if (snapshot?.fieldDigestAlgorithm !== "sha256-stable-json-v1" || snapshot?.fieldDigest !== digestStable(snapshot?.claim)) reasons.push("fieldDigestInvalid");
    if (snapshot?.claim?.transitionId !== "genshin:6.7->7.0" || snapshot?.claim?.fromGameVersion !== "6.7" || snapshot?.claim?.toGameVersion !== "7.0") reasons.push("transitionBindingInvalid");
    if (snapshot?.claim?.provider !== provider || snapshot?.claim?.sourceFamily !== sourceFamily || snapshot?.claim?.repository !== repository || snapshot?.claim?.sourceFamilyCount !== 1) reasons.push("providerBindingInvalid");
    const queue = queueShard();
    const shard = snapshot?.claim?.queueShard;
    if (!shard || shard.shardId !== queue.shardId
        || shard.queuePath !== queue.queuePath
        || shard.requestedPrimaryBlockReason !== requestedPrimaryBlockReason
        || shard.observedPrimaryBlockReason !== observedPrimaryBlockReason
        || shard.authoritativeCandidateCount !== queue.candidateCount
        || digestStable(shard.authoritativeCandidateIds) !== queue.candidateIdsDigest
        || shard.authoritativeEntityCount !== queue.entityCount
        || digestStable(shard.authoritativeEntityIds) !== queue.entityIdsDigest
        || digestStable(shard.overlapEntityIds) !== digestStable(overlapEntityIds)
        || shard.overlapPolicy !== "noneWithMaterializedBehaviorShards01To04") reasons.push("authoritativeShardBindingInvalid");
    const bindings = Array.isArray(snapshot?.claim?.versionBindings) ? snapshot.claim.versionBindings : [];
    if (bindings.length !== 2) reasons.push("versionBindingsIncomplete");
    for (const revision of Object.values(revisions)) {
        const binding = bindings.find((candidate) => candidate.gameVersion === revision.gameVersion);
        const packageValue = binding?.package;
        const packageFilePath = packageValue?.path ? path.resolve(root, packageValue.path) : null;
        if (!binding || binding.revision !== revision.revision || binding.packageVersion !== revision.packageVersion || binding.status !== "strictlyBound" || !packageFilePath || !fs.existsSync(packageFilePath)) {
            reasons.push(`versionBindingInvalid:${revision.gameVersion}`);
            continue;
        }
        const bytes = fs.readFileSync(packageFilePath);
        if (bytes.length !== revision.packageBytes || sha256(bytes) !== revision.packageDigest || gitBlobSha(bytes) !== revision.packageBlob) reasons.push(`packageBindingInvalid:${revision.gameVersion}`);
        try {
            const manifest = assertExpectedPackage(revision, bytes);
            if (packageValue.name !== manifest.name || packageValue.description !== manifest.description) reasons.push(`packageMetadataInvalid:${revision.gameVersion}`);
        } catch (error) {
            reasons.push(`packageJsonInvalid:${revision.gameVersion}:${error.message}`);
        }
    }
    const entities = Array.isArray(snapshot?.claim?.resolvedEntities) ? snapshot.claim.resolvedEntities : [];
    if (entities.length !== resolvedEntities.length || new Set(entities.map((entity) => entity.entityId)).size !== entities.length) reasons.push("resolvedEntitiesIncomplete");
    for (const expected of resolvedEntities) {
        const entity = entities.find((candidate) => candidate.entityId === expected.entityId);
        if (!entity || entity.name !== expected.name || entity.nameJa !== expected.nameJa || entity.providerSlug !== expected.slug || entity.resolutionStatus !== "resolvedUnambiguousByProviderName") {
            reasons.push(`resolvedEntityInvalid:${expected.entityId}`);
            continue;
        }
        if (!Array.isArray(entity.records) || entity.records.length !== recordKinds.length) {
            reasons.push(`recordsIncomplete:${expected.entityId}`);
            continue;
        }
        for (const recordKind of recordKinds) {
            const record = entity.records.find((candidate) => candidate.recordKind === recordKind);
            if (!record) {
                reasons.push(`recordMissing:${expected.entityId}:${recordKind}`);
                continue;
            }
            for (const side of ["before", "after"]) {
                const revision = side === "before" ? revisions.before : revisions.after;
                reasons.push(...validateArtifact(record[side], revision, expected, recordKind, root).map((reason) => `${expected.entityId}:${recordKind}:${side}:${reason}`));
            }
            const beforeFile = path.resolve(root, record.before?.path || "");
            const afterFile = path.resolve(root, record.after?.path || "");
            if (fs.existsSync(beforeFile) && fs.existsSync(afterFile)) {
                const before = readJson(beforeFile);
                const after = readJson(afterFile);
                const diffs = fieldDiffs(before, after);
                if (record.comparison?.status !== (diffs.length ? "rawRecordChanged" : "rawRecordMatch")
                    || record.comparison?.beforeNormalizedRecordDigest !== digestStable(before)
                    || record.comparison?.afterNormalizedRecordDigest !== digestStable(after)
                    || record.comparison?.changedFieldCount !== diffs.length
                    || digestStable(record.comparison?.fieldDiffs) !== digestStable(diffs)) reasons.push(`comparisonInvalid:${expected.entityId}:${recordKind}`);
            }
        }
    }
    if (!Array.isArray(snapshot?.claim?.travelerVariantEvidence) || snapshot.claim.travelerVariantEvidence.length !== 0) reasons.push("travelerVariantEvidenceUnexpected");
    if (!Array.isArray(snapshot?.claim?.variantAmbiguities) || snapshot.claim.variantAmbiguities.length !== 0) reasons.push("variantAmbiguitiesUnexpected");
    if (snapshot?.claim?.coverage?.canIssueEligibilityCertificate !== false || snapshot.claim.coverage.canPromoteCanonical !== false
        || snapshot?.gateEligibility?.canIssueEligibilityCertificate !== false || snapshot?.gateEligibility?.canPromoteCanonical !== false) reasons.push("failClosedDispositionInvalid");
    return { valid: reasons.length === 0, reasons };
}

function buildCheckpoint(snapshot = buildSnapshot()) {
    const queue = queueShard();
    const ids = snapshot.claim.queueShard.authoritativeEntityIds;
    const revisionProgress = (revision) => ({
        gameVersion: revision.gameVersion,
        revision: revision.revision,
        status: "complete",
        completedEntityIds: ids,
        completedArtifactCount: ids.length * recordKinds.length
    });
    const claim = {
        queueShardId: snapshot.claim.queueShard.shardId,
        queuePath: snapshot.claim.queueShard.queuePath,
        requestedPrimaryBlockReason,
        observedPrimaryBlockReason,
        requestedEntityIds: ids,
        overlapEntityIds,
        materializedSnapshotPath: relative(outputPath),
        materializedSnapshotFieldDigest: snapshot.fieldDigest,
        sourceFamilyCount: 1,
        canIssueEligibilityCertificate: false,
        canPromoteCanonical: false
    };
    return {
        schemaVersion: 1,
        kind: "genshinVersionTransitionBehaviorShard06CaptureCheckpoint",
        generatedAt,
        transitionId: "genshin:6.7->7.0",
        status: "complete",
        requestedEntityCount: ids.length,
        requestedEntityIds: ids,
        overlapEntityIds,
        queueShard: {
            shardId: snapshot.claim.queueShard.shardId,
            candidateCount: queue.candidateCount,
            candidateIdsDigest: queue.candidateIdsDigest,
            observedPrimaryBlockReason
        },
        revisions: {
            before: revisionProgress(revisions.before),
            after: revisionProgress(revisions.after)
        },
        nextTask: "Acquire independent strictly 7.0-bound field evidence and reconcile behavior semantics; no automatic promotion from this correlated capture.",
        blocker: {
            status: "sourceCapturedSingleCorrelatedFamily",
            reasons: ["providerIndependenceInsufficient", "behaviorSemanticsNotParsed", "noIndependentSourceFamily"]
        },
        materializedSnapshot: {
            path: relative(outputPath),
            fieldDigest: snapshot.fieldDigest,
            entityCount: snapshot.summary.resolvedEntities,
            recordCount: snapshot.summary.resolvedRecords,
            normalizedRecordsChanged: snapshot.summary.changedRecords
        },
        gateEligibility: {
            sourceFamilyCount: 1,
            canIssueEligibilityCertificate: false,
            canPromoteCanonical: false
        },
        claim,
        fieldDigestAlgorithm: "sha256-stable-json-v1",
        fieldDigest: digestStable(claim)
    };
}

function validateBehaviorShard06Checkpoint(checkpoint, { repositoryRoot: root = repositoryRoot } = {}) {
    const reasons = [];
    if (checkpoint?.schemaVersion !== 1 || checkpoint?.kind !== "genshinVersionTransitionBehaviorShard06CaptureCheckpoint") reasons.push("identityInvalid");
    if (checkpoint?.generatedAt !== generatedAt) reasons.push("generatedAtInvalid");
    if (checkpoint?.transitionId !== "genshin:6.7->7.0" || checkpoint?.status !== "complete") reasons.push("statusInvalid");
    if (checkpoint?.fieldDigestAlgorithm !== "sha256-stable-json-v1" || checkpoint?.fieldDigest !== digestStable(checkpoint?.claim)) reasons.push("fieldDigestInvalid");
    const queue = queueShard();
    if (checkpoint?.requestedEntityCount !== queue.entityCount || digestStable(checkpoint?.requestedEntityIds) !== queue.entityIdsDigest
        || digestStable(checkpoint?.overlapEntityIds) !== digestStable(overlapEntityIds)) reasons.push("entityInventoryInvalid");
    if (checkpoint?.queueShard?.shardId !== queue.shardId || checkpoint?.queueShard?.candidateCount !== queue.candidateCount || checkpoint?.queueShard?.candidateIdsDigest !== queue.candidateIdsDigest
        || checkpoint?.queueShard?.observedPrimaryBlockReason !== observedPrimaryBlockReason) reasons.push("queueShardInvalid");
    for (const [side, revision] of Object.entries(revisions)) {
        const progress = checkpoint?.revisions?.[side];
        if (!progress || progress.gameVersion !== revision.gameVersion || progress.revision !== revision.revision || progress.status !== "complete"
            || digestStable(progress.completedEntityIds) !== queue.entityIdsDigest || progress.completedArtifactCount !== queue.entityCount * recordKinds.length) reasons.push(`revisionProgressInvalid:${side}`);
    }
    const materializedPath = checkpoint?.materializedSnapshot?.path ? path.resolve(root, checkpoint.materializedSnapshot.path) : null;
    if (!materializedPath || !fs.existsSync(materializedPath)) reasons.push("materializedSnapshotMissing");
    else {
        const snapshot = readJson(materializedPath);
        if (checkpoint.materializedSnapshot.fieldDigest !== snapshot.fieldDigest || validateBehaviorShard06Snapshot(snapshot, { repositoryRoot: root }).valid !== true) reasons.push("materializedSnapshotInvalid");
    }
    if (checkpoint?.claim?.requestedPrimaryBlockReason !== requestedPrimaryBlockReason || checkpoint?.claim?.observedPrimaryBlockReason !== observedPrimaryBlockReason
        || checkpoint?.claim?.sourceFamilyCount !== 1 || checkpoint?.claim?.canIssueEligibilityCertificate !== false || checkpoint?.claim?.canPromoteCanonical !== false
        || checkpoint?.gateEligibility?.sourceFamilyCount !== 1 || checkpoint?.gateEligibility?.canIssueEligibilityCertificate !== false || checkpoint?.gateEligibility?.canPromoteCanonical !== false) reasons.push("failClosedDispositionInvalid");
    return { valid: reasons.length === 0, reasons };
}

function writeSnapshot() {
    const snapshot = buildSnapshot();
    const checkpoint = buildCheckpoint(snapshot);
    fs.writeFileSync(outputPath, `${JSON.stringify(snapshot, null, 2)}\n`, "utf8");
    fs.writeFileSync(checkpointPath, `${JSON.stringify(checkpoint, null, 2)}\n`, "utf8");
    return { snapshot, checkpoint };
}

async function main() {
    if (process.argv.includes("--fetch")) await acquire();
    const result = writeSnapshot();
    process.stdout.write(`${JSON.stringify(result.snapshot.summary, null, 2)}\n`);
}

if (require.main === module) main().catch((error) => {
    process.stderr.write(`${error.stack || error.message}\n`);
    process.exitCode = 1;
});

module.exports = {
    acquire,
    buildCheckpoint,
    buildSnapshot,
    checkpointPath,
    generatedAt,
    outputPath,
    overlapEntityIds,
    queueShard,
    recordKinds,
    resolvedEntities,
    revisions,
    shardId,
    validateBehaviorShard06Checkpoint,
    validateBehaviorShard06Snapshot,
    writeSnapshot
};
